config/routes.rb
Rails.application.routes.draw do
  resources :authentications

  devise_for :users, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  root 'welcome#index'
  get '/auth/:provider/callback' => 'authentications#create'
  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user

	
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :locatable, polymorphic: true
  acts_as_mappable  default_units: :kms
end

app/models/milestone.rb
class Milestone < TripEvent

  validates :road_condition, presence: true, inclusion: { in: [:horrible, :bad, :good, :excellent] }

  def road_condition
    read_attribute(:road_condition).to_sym
  end

  def road_condition=value
    write_attribute(:road_condition, value.to_s)
  end

  def to_s
    "Milestone: #{description}"
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  extend FriendlyId
  belongs_to :user
  friendly_id :name, use: :scoped, scope: :user
  has_many :trip_events

  validates :name, presence: true
  validates :transport, inclusion: { in: [:car, :motorcycle, :bus, :bicycle, :other] }
  validates :user, presence: true

  validates_associated :trip_events
  delegate :milestones, to: :trip_events

  def transport
    read_attribute(:transport).to_sym
  end

  def transport=value
    write_attribute(:transport, value.to_s)
  end
end

app/models/trip_event.rb
class TripEvent < ActiveRecord::Base
  include RankedModel

  default_scope { order(:order) }

  belongs_to :trip
  has_one :location, as: :locatable
  ranks :order, with_same: :trip_id

  validates :trip, presence: true
  validates :location, presence: true

  scope :milestones, -> { where(type: 'Milestone') }
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :trips
  has_many :authentications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,  presence: true,
                        length: {
                          minimum: 4,
                          maximum: 15
                        }
  validates :gender, inclusion: { in: [:male, :female] }

  def apply_omniauth(omniauth)
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def gender
    read_attribute(:gender).to_sym
  end

  def gender=value
    write_attribute(:gender, value.to_s)
  end

  def password_required?
  (authentications.empty? || !password.blank?) && super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_action :set_authentication, only: [:show, :edit, :update, :destroy]


  def index
    @authentications = current_user.authentications if current_user
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
  end

  # GET /authentications/new
  def new
    @authentication = Authentication.new
  end

  # GET /authentications/1/edit
  def edit
  end

    # POST /authentications

  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)

      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br>
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<% "Sign In" %>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<a href="/auth/google_oauth2" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  Google
</a>
<div class="clear"></div>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @authentication.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @authentication.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @authentication.uid %>
</p>

<p>
  <strong>Index:</strong>
  <%= @authentication.index %>
</p>

<p>
  <strong>Create:</strong>
  <%= @authentication.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @authentication.destroy %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RoadMojo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "RoadMojo" %>">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>    
    
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%- flash.each do |name, msg| -%>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <%- end -%>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello!</h1>